import { Router, type IRouter } from "express";
import { z } from "zod/v4";
import { guardTargetUrl } from "../lib/net-guard";
import { logger } from "../lib/logger";

const router: IRouter = Router();

/** Hop-by-hop and browser-managed headers that must not be forwarded. */
const STRIPPED_REQUEST_HEADERS = new Set([
  "host",
  "connection",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
  "content-length",
  "accept-encoding",
]);

const STRIPPED_RESPONSE_HEADERS = new Set([
  "connection",
  "keep-alive",
  "transfer-encoding",
  "content-encoding",
]);

const MAX_RESPONSE_BYTES = 8 * 1024 * 1024;
const MAX_TIMEOUT_MS = 120_000;

const KeyValue = z.object({ key: z.string(), value: z.string() });

const ProxyRequest = z.object({
  method: z.enum(["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]),
  url: z.string().min(1),
  headers: z.array(KeyValue).max(100).default([]),
  body: z
    .discriminatedUnion("type", [
      z.object({ type: z.literal("none") }),
      z.object({ type: z.literal("text"), text: z.string(), contentType: z.string().default("") }),
      z.object({ type: z.literal("form"), fields: z.array(KeyValue).max(200) }),
      z.object({ type: z.literal("multipart"), fields: z.array(KeyValue).max(200) }),
    ])
    .default({ type: "none" }),
  timeoutMs: z.number().int().positive().max(MAX_TIMEOUT_MS).default(30_000),
  followRedirects: z.boolean().default(true),
});

type ProxyBody = z.infer<typeof ProxyRequest>["body"];

/** `BodyInit` is a DOM type, so spell out the shapes the proxy actually sends. */
type UpstreamBody = string | URLSearchParams | FormData | undefined;

function buildBody(body: ProxyBody): UpstreamBody {
  switch (body.type) {
    case "none":
      return undefined;
    case "text":
      return body.text;
    case "form": {
      const search = new URLSearchParams();
      for (const field of body.fields) search.append(field.key, field.value);
      return search;
    }
    case "multipart": {
      const form = new FormData();
      for (const field of body.fields) form.append(field.key, field.value);
      return form;
    }
  }
}

/**
 * Forward one HTTP request and return the raw result.
 *
 * The browser cannot call arbitrary third-party APIs without their CORS
 * cooperation; doing the call here is what lets the workbench behave like a
 * desktop client.
 */
router.post("/proxy", async (req, res) => {
  const parsed = ProxyRequest.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({
      error: { code: "invalid_request", message: z.prettifyError(parsed.error) },
    });
    return;
  }

  const input = parsed.data;
  const guard = await guardTargetUrl(input.url);
  if (!guard.ok) {
    res.status(400).json({ error: { code: "blocked_target", message: guard.reason } });
    return;
  }

  const headers = new Headers();
  for (const header of input.headers) {
    const name = header.key.trim();
    if (!name || STRIPPED_REQUEST_HEADERS.has(name.toLowerCase())) continue;
    // multipart boundaries are generated by fetch, so never forward ours.
    if (input.body.type === "multipart" && name.toLowerCase() === "content-type") continue;
    try {
      headers.append(name, header.value);
    } catch {
      res.status(400).json({ error: { code: "invalid_header", message: `Header "${name}" is not valid.` } });
      return;
    }
  }
  if (input.body.type === "text" && input.body.contentType && !headers.has("content-type")) {
    headers.set("content-type", input.body.contentType);
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), input.timeoutMs);
  const started = performance.now();

  try {
    const upstream = await fetch(guard.url, {
      method: input.method,
      headers,
      body: buildBody(input.body),
      redirect: input.followRedirects ? "follow" : "manual",
      signal: controller.signal,
    });

    const buffer = Buffer.from(await upstream.arrayBuffer());
    const truncated = buffer.byteLength > MAX_RESPONSE_BYTES;
    const body = buffer.subarray(0, MAX_RESPONSE_BYTES).toString("utf8");

    const responseHeaders: Array<{ key: string; value: string }> = [];
    upstream.headers.forEach((value, key) => {
      if (STRIPPED_RESPONSE_HEADERS.has(key.toLowerCase())) return;
      responseHeaders.push({ key, value });
    });
    // `Headers` folds duplicate set-cookie values together; getSetCookie keeps them apart.
    const setCookies = upstream.headers.getSetCookie?.() ?? [];
    if (setCookies.length > 0) {
      for (let index = responseHeaders.length - 1; index >= 0; index -= 1) {
        if (responseHeaders[index]!.key.toLowerCase() === "set-cookie") responseHeaders.splice(index, 1);
      }
      for (const cookie of setCookies) responseHeaders.push({ key: "set-cookie", value: cookie });
    }

    res.json({
      status: upstream.status,
      statusText: upstream.statusText,
      headers: responseHeaders,
      body,
      truncated,
      size: buffer.byteLength,
      durationMs: Math.round(performance.now() - started),
      finalUrl: upstream.url || guard.url.toString(),
    });
  } catch (error) {
    const aborted = error instanceof Error && error.name === "AbortError";
    logger.warn({ err: error, host: guard.url.host }, "Proxy request failed");
    res.status(aborted ? 504 : 502).json({
      error: {
        code: aborted ? "upstream_timeout" : "upstream_unreachable",
        message: aborted
          ? `The upstream did not respond within ${input.timeoutMs} ms.`
          : error instanceof Error
            ? error.message
            : "The upstream request failed.",
      },
    });
  } finally {
    clearTimeout(timeout);
  }
});

export default router;
